<?php defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * @author Ivan Tcholakov <ivantcholakov@gmail.com>, 2015-2016
 * @license The MIT License, http://opensource.org/licenses/MIT
 *
 * @see https://github.com/pyrocms/lex
 */

// The character(s) used by Lex to trigger a scope change. A scope change is,
// for instance accessing a nested variable inside and array/object,
$config['scope_glue'] = ':';

// Sets the noparse style; FALSE - immediate, TRUE - cumulative.
$config['cumulative_noparse'] = false;


// Lex Parser Extensions

// A blacklist of configuration options that Lex parser should not access.
$config['disabled_config_settings'] = array(

    // Common
    'password',
    'encryption',

    // Speciric
    'uri_protocol',
    'url_suffix',
    'enable_hooks',
    'subclass_prefix',
    'composer_autoload',
    'permitted_uri_chars',
    'allow_get_array',
    'enable_query_strings',
    'controller_trigger',
    'function_trigger',
    'directory_trigger',
    'log_threshold',
    'log_path',
    'log_file_extension',
    'log_file_permissions',
    'log_date_format',
    'error_views_path',
    'cache_path',
    'cache_query_string',
    'encryption_key',
    'encryption_key_256',
    'encryption_key_for_settings',
    'sess_driver',
    'sess_cookie_name',
    'sess_expiration',
    'sess_save_path',
    'sess_match_ip',
    'sess_time_to_update',
    'sess_regenerate_destroy',
    'standardize_newlines',
    'global_xss_filtering',
    'csrf_protection',
    'csrf_token_name',
    'csrf_cookie_name',
    'csrf_expire',
    'csrf_regenerate',
    'csrf_exclude_uris',
    'rewrite_short_tags',
    'proxy_ips',
    'controller_suffix',
    'modules_locations',
    'public_upload_path',
    'platform_upload_path',
);

// A whitelist of constants that Lex parser can access.
$config['allowed_globals'] = array(
    'BASE_URL',
    'BASE_URI',
    'SERVER_URL',
    'SITE_URL',
    'SITE_URI',
    'CURRENT_SITE_URL',
    'CURRENT_SITE_URI',
    'CURRENT_URL',
    'CURRENT_URI',
    'CURRENT_URL_IS_HTTPS',
    'CURRENT_URL_PROTOCOL',
    'CURRENT_URL_HOST',
    'CURRENT_URL_PORT',
    'CURRENT_URI_STRING',
    'CURRENT_QUERY_STRING',
    'DEFAULT_BASE_URL',
    'DEFAULT_BASE_URI',
    'ASSET_URL',
    'ASSET_URI',
    'THEME_ASSET_URL',
    'THEME_ASSET_URI',
    'ASSET_IMG_URL',
    'ASSET_IMG_URI',
    'ASSET_JS_URL',
    'ASSET_JS_URI',
    'ASSET_CSS_URL',
    'ASSET_CSS_URI',
    'THEME_IMG_URL',
    'THEME_IMG_URI',
    'THEME_JS_URL',
    'THEME_JS_URI',
    'THEME_CSS_URL',
    'THEME_CSS_URI',
    'PUBLIC_UPLOAD_URL',
    'UA_IS_MOBILE',
    'UA_IS_ROBOT',
    'UA_IS_REFERRAL',
    'CI_VERSION',
    'PLATFORM_VERSION',
    'ENVIRONMENT',
);

// A whitelist of functions that Lex parser can execute.
$config['allowed_functions'] = array(
    'character_limiter',
    'count',
    'date',
    'empty',
    'explode',
    'gettype',
    'gmap_url',
    'highlight_phrase',
    'html_entity_decode',
    'html_escape',
    'htmlentities',
    'htmlspecialchars',
    'htmlspecialchars_decode',
    'humanize',
    'implode',
    'is_array',
    'is_bool',
    'is_boolean',
    'is_float',
    'is_https',
    'is_int',
    'is_integer',
    'is_null',
    'is_numeric',
    'is_object',
    'is_scalar',
    'is_string',
    'isset',
    'json_decode',
    'json_encode',
    'ltrim',
    'md5',
    'money_format',
    'nl2br',
    'number_format',
    'preg_match',
    'preg_match_all',
    'preg_replace',
    'print_d',
    'print_r',
    'rand_string',
    'rtrim',
    'safe_mailto',
    'slugify',
    'sha1',
    'sprintf',
    'str_replace',
    'strip_tags',
    'stripos',
    'strlen',
    'strpos',
    'strtolower',
    'strtoupper',
    'substr',
    'timespan',
    'trim',
    'ucfirst',
    'ucwords',
    'url_title',
    'var_dump',
    'var_export',
    'word_limiter',
    'word_wrap', // CodeIgniter
    'wordwrap',  // PHP
);
